#!/usr/bin/python3

import sys
import random
import time

def prime_check(number):
    if number < 2 or number == 0:
        return False
    for i in range(2, int(sqrt(number)) + 1):
        if number % i == 0:
            return False
    return True

        